trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

parameters:
- name: runTests
  displayName: Run tests
  type: boolean
  default: true
- name: runOWASPScan
  displayName: Run OWASP Scan
  type: boolean
  default: false
- name: sonarqubeInstance
  displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
  type: string
  default: 'SonarQubeLatest'
  values:
  - 'SonarQube'
  - 'SonarQubeLatest'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: ''                 # Example 'EPR.Payment.Mopup'-- Remove this comment
  - name: testProjectFolder
    value: ''                 # Example 'EPR.Payment.Mopup.Common.UnitTests'-- Remove this comment
# ---------------------------------------------------------------------------------------------------------------------- 
# DB Pipeline step - this is only needed if there is an sql pipeline - if not remove the line of code and this comments
  - name: DataFolder
    value: ''                 # Example 'EPR.Payment.Mopup.Common.Data'-- Remove this comment
# Remove comments once completed
# -----------------------------------------------------------------------------------------------------------------------
  - name: sonarQubeProjectKey
    value:                     # Example: epr-prn-obligationcalculations-function -- Remove this comment
  - name: sonarQubeProjectName
    value:                     # Example: epr-prn-obligationcalculations-function -- Remove this comment
  - name: runNugetTasks
# ----------------------------------------------------------------------------------------------------------------------- 
# Set the NuGet Task to TRUE only for Frontend, else FALSE -  remove this comments
    value: false
# ----------------------------------------------------------------------------------------------------------------------- 
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: main

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
# ---------------------------------------------------------------------------------------------------------------------- 
# DB Pipeline step - this is only needed if there is an sql pipeline - if not remove the line of code and this comments
    DataFolder: ${{ variables.DataFolder }}
# ----------------------------------------------------------------------------------------------------------------------- 
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ parameters.runTests }}
    runOWASPScan: ${{ parameters.runOWASPScan }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
# ---------------------------------------------------------------------------------------------------------------------- 
# DB Pipeline step - this is only needed if there is an sql pipeline - if not remove the line of code or set to FALSE and this comments
    buildMigrationScript: true
# ----------------------------------------------------------------------------------------------------------------------- 
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
    dotnetVersion: ${{ variables.dotnetVersion }}
