variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: ''      # Example 'epranyimagename' same name as in development -- Remove this comment
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: ''    # Example 'epranyimagenamerepository' same name as in development -- Remove this comment
  serviceName: ''           # Example 'PRDRWDWEBFA1410', this service name will always have a 1 after the letter A -- Remove this comment